# USER SETTINGS
RECORDING_DIR: "" # Leave blank to use default directory
USE_BLACKLIST: True
BLACKLISTED_APPS:
  - Google Chrome
  - WhatsApp
  - Messenger
  - Discord
  - To Do
  - Steam
  - Spotify
  

USE_AUTOSTART: True
USE_AUTOSTOP: True
AUTOSTART_APPS:
  - Visual Studio Code
  - Github Desktop
  - Autodesk Inventor Professional 2023
  - Blender
  - Ultimaker Cura

AUTOSTART_OVERRIDES_BLACKLIST: True

# ADVANCED SETTINGS
INPUT_FPS: 15
OUTPUT_FPS: 60
THUMBNAIL_REDUCTION: 4 # reduces thumbnail size 2560x1440 -> 640x360
THUMBNAIL_INTERVAL: 150 # Every n seconds, record a second of thumbnail