AUTOTRIGGER_APPS:
- Google Chrome
- Visual Studio Code
- Blender
- Cura
- Autodesk Inventor Professional 2023
BLACKLISTED_APPS:
- YouTube
- Porn
- Gmail
HOME_DIR: C:\Users\axel1\Videos\SempRecord
INPUT_FPS: 20
OUTPUT_FPS: 60
THUMBNAIL_INTERVAL: 150
THUMB_REDUCE_FACTOR: 5
USE_AUTOTRIGGER: false
USE_BLACKLIST: true
USE_WHITELIST: true
WHITELISTED_APPS: []
