# USER SETTINGS
RECORDING_DIR: r"C:\Users\axel1\Videos\Records"
USE_BLACKLIST: True
BLACKLISTED_APPS:
  - Google Chrome
  - WhatsApp
  - Messenger
  - Discord
  - To Do
  - Steam
  - Spotify
  

USE_AUTOSTART: True
AUTOSTART_APPS:
  - Visual Studio Code
  - Github Desktop
  - Autodesk Inventor Professional 2023
  - Blender
  - Ultimaker Cura 

# ADVANCED SETTINGS
INPUT_FPS: 15
OUTPUT_FPS: 60
THUMBNAIL_REDUCTION: 4 # reduces thumbnail size 2560x1440 -> 640x360
THUMBNAIL_INTERVAL: 150 # Every n seconds, record a second of thumbnail