AUTOTRIGGER_APPS:
- Google Chrome
- Visual Studio Code
HOME_DIR: C:\Users\axel1\Videos\SempRecord
INPUT_FPS: 10
OUTPUT_FPS: 60
THUMBNAIL_INTERVAL: 150
THUMB_REDUCE_FACTOR: 5
USE_AUTOTRIGGER: false
USE_WHITELIST: false
WHITELISTED_APPS: []
